# Generated by Django 6.1.1 on 2026-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_student_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
    ]
